# Generated by Django 4.2 on 2023-04-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('sub', models.CharField(max_length=200)),
                ('first', models.TextField()),
                ('second', models.TextField(blank=True)),
                ('third', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='')),
                ('simage', models.ImageField(blank=True, upload_to='')),
                ('Date', models.DateField()),
            ],
        ),
    ]
