# Generated by Django 4.2 on 2023-04-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteos', '0002_rename_date_post_date_post_bibliography'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
